---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "seurat_visualisation"
## TODO nf-core: Add a description of the module and list keywords
description: write your description here
keywords:
  - sort
  - example
  - genomics
tools:
  - "seurat":
      ## TODO nf-core: Add a description and other details for the software below
      description: "A toolkit for quality control, analysis, and exploration of single cell RNA sequencing data. 'Seurat' aims to enable users to identify and interpret sources of heterogeneity from single cell transcriptomic measurements, and to integrate diverse types of single cell data. See Satija R, Farrell J, Gennert D, et al (2015) <doi:10.1038/nbt.3192>, Macosko E, Basu A, Satija R, et al (2015) <doi:10.1016/j.cell.2015.05.002>, and Butler A and Satija R (2017) <doi:10.1101/164889> for more details."
      homepage: "None"
      documentation: "None"
      tool_dev_url: "https://github.com/satijalab/seurat"
      doi: ""
      licence: ['GPL v3']

## TODO nf-core: Add a description of all of the variables used as input
input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  
  ## TODO nf-core: Delete / customise this example input
  - bam:
      type: file
      description: Sorted BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"

## TODO nf-core: Add a description of all of the variables used as output
output:
  #Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - ridgePlot: 
      type: file
      description: File containing the ridge plot of the assignment (optional)
      pattern: "*.jpeg"
  - featureScatter: 
      type: file
      description: File containing the feature scatter plot of the assignment (optional)
      pattern: "*.jpeg"
  - violingPlot: 
      type: file
      description: File containing the violing plot of the assignment (optional)
      pattern: "*.jpeg"
  - tSNEPlot:
      type: file
      description: File containing the tSNE plot of the assignment (optional)
      pattern: "*.jpeg"

authors:
  - "@mari-ga"
maintainers:
  - "@mari-ga"
